# Generated by Django 4.1.6 on 2023-02-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='btc_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Open', models.FloatField()),
                ('Close', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Volume', models.FloatField()),
            ],
        ),
    ]
